version: 2.0
workflows:
  ios-build:
    name: Build iOS App
    max_build_duration: 60 # in minutes
    environment:
      xcode: "15.0" # Убедитесь, что используете нужную версию Xcode
    scripts:
      - name: Check xcodebuild version
        script: xcodebuild -version
      - name: Check CocoaPods version
        script: pod --version
      - name: Install dependencies
        script: |
          gem install cocoapods
          pod install
      - name: Build iOS App
        script: |
          xcodebuild -workspace Pyto.xcworkspace -scheme Pyto -sdk iphoneos -configuration AppStoreDistribution archive -archivePath $CM_BUILD_DIR/Pyto.xcarchive
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/Pyto.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $CM_BUILD_DIR
      - name: List contents of build directory
        script: ls -la $CM_BUILD_DIR
    artifacts:
      - $CM_BUILD_DIR/Pyto.ipa
