version: 2.0

workflows:
  ios-build:
    name: Build iOS App
    max_build_duration: 60 # Время в минутах
    environment:
      xcode: "15.0" # Убедитесь, что используете нужную версию Xcode
    scripts:
      - name: Install dependencies
        script: |
          gem install cocoapods
          pod install
      - name: Decode certificates
        script: |
          echo $CERTIFICATE_P12 | base64 --decode > certificate.p12
          echo $PRIVATE_KEY | base64 --decode > private_key.key
      - name: Setup Keychain
        script: |
          # Создание и настройка Keychain
          security create-keychain -p "keychain_password" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "keychain_password" build.keychain

          # Импорт сертификата и ключа в Keychain
          security import certificate.p12 -k ~/Library/Keychains/build.keychain -P "certificate_password" -A
          security import private_key.key -k ~/Library/Keychains/build.keychain -P "private_key_password" -A

          # Настройка Keychain
          security list-keychains -d user -s ~/Library/Keychains/build.keychain
          security set-keychain-settings -t 3600 -l ~/Library/Keychains/build.keychain
      - name: Build iOS App
        script: |
          xcodebuild -workspace Pyto.xcworkspace -scheme Pyto -sdk iphoneos -configuration AppStoreDistribution archive -archivePath $CM_BUILD_DIR/Pyto.xcarchive
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/Pyto.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $CM_BUILD_DIR
    artifacts:
      - $CM_BUILD_DIR/Pyto.ipa
